backend:
  name: github
  repo: savvops/nano-nodes
  branch: main
  base_url: https://pages.cms.cloud # or custom auth proxy if required by pages CMS
  auth_endpoint: auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
